# best-of-N
model_id: cognition-ai/Kevin-32B
technique: best_of_n
n_samples: 4
level: 1
problem_id: 1
dataset_source: huggingface
num_correct_trials: 5
num_perf_trials: 100
precision: fp32
backend: cuda
prompt_option: one_shot
max_new_tokens: 768
temperature: 0.6
